FROM continuumio/miniconda3

# Crea un entorno con Python 3.9 y activa conda
RUN conda create -n microbioma python=3.9 -y
SHELL ["conda", "run", "-n", "microbioma", "/bin/bash", "-c"]

# Instala dependencias del sistema y del entorno
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Instala librerías necesarias con conda y pip
COPY requirements.txt .
RUN conda install -n microbioma -y -c conda-forge scikit-bio pandas numpy && \
    pip install --no-cache-dir -r requirements.txt

# Establece el directorio de trabajo
WORKDIR /app

COPY myapp/ myapp/

# Expone el puerto de FastAPI
EXPOSE 8000

# Comando de inicio
CMD ["conda", "run", "-n", "microbioma", "uvicorn", "myapp.main:app", "--host", "0.0.0.0", "--port", "8000"]
