version: '3'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - mynetwork 

  fastapi:
    image: dockerfile-fastapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    ports:
      - 8000:8000
    volumes:
      - ./myapp:/app/myapp
    depends_on:
      - db
      - redis
    networks:
      - mynetwork 

  celery-worker:
    image: dockerfile-celery-worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    volumes:
      - ./myapp:/app/myapp
    depends_on:
      - redis
    networks:
      - mynetwork 

  celery-beat:
    image: dockerfile-celery-beat
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-celery-beat
    volumes:
      - ./myapp:/app/myapp
    depends_on:
      - redis
    networks:
      - mynetwork 

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis:/var/lib/redis/data
    networks:
      - mynetwork
 

  celery-flower:
    image: dockerfile-celery-flower
    build:
      context: .
      dockerfile: Dockerfile-celery-flower
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery-worker
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
