# Utiliza la imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY requirements.txt .
COPY myapp/ myapp/

# Instala las dependencias de la aplicación 
RUN pip install --no-cache-dir -r requirements.txt 

# Inicia Celery Beat
CMD ["celery", "-A", "myapp.celery", "beat", "--loglevel=info"]

