# Utiliza la imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY requirements.txt .
COPY myapp/ myapp/

#RUN apt-get update && apt-get install -y r-base r-base-dev cmake r-cran-rcppeigen
#RUN sh myapp/Rscripts/installR.sh
#RUN Rscript --vanilla myapp/Rscripts/install_packages.R

# Instala las dependencias de la aplicación
RUN pip install --no-cache-dir -r requirements.txt 


# Inicia el Celery Worker
CMD ["celery", "-A", "myapp.celery", "worker", "--loglevel=info"]
