# Utiliza la imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY requirements.txt .
COPY myapp/ myapp/

# Instala las dependencias de la aplicación
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto 8000 (el puerto en el que se ejecuta FastAPI)
EXPOSE 8000

# Inicia la aplicación FastAPI
CMD ["uvicorn", "myapp.main:app", "--host", "0.0.0.0", "--port", "8000"]
