name: Run Backend Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: microdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microdb


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar compiladores y librerías del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libblas-dev liblapack-dev gfortran libgfortran5

    - name: Instalar Cython y NumPy (necesarios antes de scikit-bio)
      run: |
        pip install cython==3.0.10 numpy==1.24.4

    - name: Instalar dependencias del proyecto
      run: |
        pip install -r backend/requirements.txt

    - name: Ejecutar tests
      run: |
        PYTHONPATH=backend pytest backend/tests/
