name: Run Backend Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar compiladores y librerías del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libblas-dev liblapack-dev gfortran libgfortran3

    - name: Instalar Cython y NumPy (necesarios antes de scikit-bio)
      run: |
        pip install cython==3.0.10 numpy==1.24.4

    - name: Instalar dependencias del proyecto
      run: |
        pip install -r backend/requirements.txt

    - name: Ejecutar tests
      run: |
        PYTHONPATH=backend pytest backend/tests/
